/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Biochemistry.incarnation.tutorial;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
